export const SET_USER = 'SET_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const CHECK_AUTH = 'CHECK_AUTH';
export const SAVE_USER_IN_LOCAL_STORAGE = 'SAVE_USER_IN_LOCAL_STORAGE';
export const DELETE_USER_FROM_LOCAL_STORE = 'DELETE_USER_FROM_LOCAL_STORE';

export const WRONG_PASSWORD = 'WRONG_PASSWORD';
export const USER_NOT_EXIST = 'USER_NOT_EXIST';