export const SET_VEHICLE = 'SET_VEHICLE';
export const UPDATE_VEHICLE_PROP = 'UPDATE_VEHICLE_PROP';
export const DELETE_VEHICLE_PROP = 'DELETE_VEHICLE_PROP';
export const ADD_VEHICLE_PROP = 'ADD_VEHICLE_PROP';

export const SET_VEHICLE_ADDITIONAL_IMAGES = 'SET_VEHICLE_ADDITIONAL_IMAGES';
export const ADD_VEHICLE_ADDITIONAL_IMAGE = 'ADD_VEHICLE_ADDITIONAL_IMAGE';
export const DELETE_VEHICLE_ADDITIONAL_IMAGE = 'DELETE_VEHICLE_ADDITIONAL_IMAGE';

export const SET_NOTES = 'SET_NOTES';
export const ADD_NOTE = 'ADD_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';